// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aggregator/customob.proto

package aggregator

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BankingProductCategory int32

const (
	BankingProductCategory_TRANS_AND_SAVINGS_ACCOUNTS BankingProductCategory = 0
	BankingProductCategory_TERM_DEPOSITS              BankingProductCategory = 1
	BankingProductCategory_TRAVEL_CARDS               BankingProductCategory = 2
	BankingProductCategory_REGULATED_TRUST_ACCOUNTS   BankingProductCategory = 3
	BankingProductCategory_RESIDENTIAL_MORTGAGES      BankingProductCategory = 4
	BankingProductCategory_CRED_AND_CHRG_CARDS        BankingProductCategory = 5
	BankingProductCategory_PERS_LOANS                 BankingProductCategory = 6
	BankingProductCategory_MARGIN_LOANS               BankingProductCategory = 7
	BankingProductCategory_LEASES                     BankingProductCategory = 8
	BankingProductCategory_TRADE_FINANCE              BankingProductCategory = 9
	BankingProductCategory_OVERDRAFTS                 BankingProductCategory = 10
	BankingProductCategory_BUSINESS_LOANS             BankingProductCategory = 11
)

var BankingProductCategory_name = map[int32]string{
	0:  "TRANS_AND_SAVINGS_ACCOUNTS",
	1:  "TERM_DEPOSITS",
	2:  "TRAVEL_CARDS",
	3:  "REGULATED_TRUST_ACCOUNTS",
	4:  "RESIDENTIAL_MORTGAGES",
	5:  "CRED_AND_CHRG_CARDS",
	6:  "PERS_LOANS",
	7:  "MARGIN_LOANS",
	8:  "LEASES",
	9:  "TRADE_FINANCE",
	10: "OVERDRAFTS",
	11: "BUSINESS_LOANS",
}

var BankingProductCategory_value = map[string]int32{
	"TRANS_AND_SAVINGS_ACCOUNTS": 0,
	"TERM_DEPOSITS":              1,
	"TRAVEL_CARDS":               2,
	"REGULATED_TRUST_ACCOUNTS":   3,
	"RESIDENTIAL_MORTGAGES":      4,
	"CRED_AND_CHRG_CARDS":        5,
	"PERS_LOANS":                 6,
	"MARGIN_LOANS":               7,
	"LEASES":                     8,
	"TRADE_FINANCE":              9,
	"OVERDRAFTS":                 10,
	"BUSINESS_LOANS":             11,
}

func (x BankingProductCategory) String() string {
	return proto.EnumName(BankingProductCategory_name, int32(x))
}

func (BankingProductCategory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f4a3e3fa51fdaf3b, []int{0}
}

type ListAccountsRequest_ListAccountsRequestOpenStatus int32

const (
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_OPEN_STATUS_OPEN   ListAccountsRequest_ListAccountsRequestOpenStatus = 0
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_OPEN_STATUS_CLOSED ListAccountsRequest_ListAccountsRequestOpenStatus = 1
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_OPEN_STATUS_ALL    ListAccountsRequest_ListAccountsRequestOpenStatus = 2
)

var ListAccountsRequest_ListAccountsRequestOpenStatus_name = map[int32]string{
	0: "LIST_ACCOUNTS_REQUEST_OPEN_STATUS_OPEN",
	1: "LIST_ACCOUNTS_REQUEST_OPEN_STATUS_CLOSED",
	2: "LIST_ACCOUNTS_REQUEST_OPEN_STATUS_ALL",
}

var ListAccountsRequest_ListAccountsRequestOpenStatus_value = map[string]int32{
	"LIST_ACCOUNTS_REQUEST_OPEN_STATUS_OPEN":   0,
	"LIST_ACCOUNTS_REQUEST_OPEN_STATUS_CLOSED": 1,
	"LIST_ACCOUNTS_REQUEST_OPEN_STATUS_ALL":    2,
}

func (x ListAccountsRequest_ListAccountsRequestOpenStatus) String() string {
	return proto.EnumName(ListAccountsRequest_ListAccountsRequestOpenStatus_name, int32(x))
}

func (ListAccountsRequest_ListAccountsRequestOpenStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f4a3e3fa51fdaf3b, []int{1, 0}
}

type ListAccountsRequest_ListAccountsRequestProductCategory int32

const (
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TRANS_AND_SAVINGS_ACCOUNTS ListAccountsRequest_ListAccountsRequestProductCategory = 0
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TERM_DEPOSITS              ListAccountsRequest_ListAccountsRequestProductCategory = 1
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TRAVEL_CARDS               ListAccountsRequest_ListAccountsRequestProductCategory = 2
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_REGULATED_TRUST_ACCOUNTS   ListAccountsRequest_ListAccountsRequestProductCategory = 3
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_RESIDENTIAL_MORTGAGES      ListAccountsRequest_ListAccountsRequestProductCategory = 4
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_CRED_AND_CHRG_CARDS        ListAccountsRequest_ListAccountsRequestProductCategory = 5
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_PERS_LOANS                 ListAccountsRequest_ListAccountsRequestProductCategory = 6
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_MARGIN_LOANS               ListAccountsRequest_ListAccountsRequestProductCategory = 7
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_LEASES                     ListAccountsRequest_ListAccountsRequestProductCategory = 8
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TRADE_FINANCE              ListAccountsRequest_ListAccountsRequestProductCategory = 9
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_OVERDRAFTS                 ListAccountsRequest_ListAccountsRequestProductCategory = 10
	ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_BUSINESS_LOANS             ListAccountsRequest_ListAccountsRequestProductCategory = 11
)

var ListAccountsRequest_ListAccountsRequestProductCategory_name = map[int32]string{
	0:  "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TRANS_AND_SAVINGS_ACCOUNTS",
	1:  "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TERM_DEPOSITS",
	2:  "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TRAVEL_CARDS",
	3:  "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_REGULATED_TRUST_ACCOUNTS",
	4:  "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_RESIDENTIAL_MORTGAGES",
	5:  "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_CRED_AND_CHRG_CARDS",
	6:  "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_PERS_LOANS",
	7:  "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_MARGIN_LOANS",
	8:  "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_LEASES",
	9:  "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TRADE_FINANCE",
	10: "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_OVERDRAFTS",
	11: "LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_BUSINESS_LOANS",
}

var ListAccountsRequest_ListAccountsRequestProductCategory_value = map[string]int32{
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TRANS_AND_SAVINGS_ACCOUNTS": 0,
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TERM_DEPOSITS":              1,
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TRAVEL_CARDS":               2,
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_REGULATED_TRUST_ACCOUNTS":   3,
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_RESIDENTIAL_MORTGAGES":      4,
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_CRED_AND_CHRG_CARDS":        5,
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_PERS_LOANS":                 6,
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_MARGIN_LOANS":               7,
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_LEASES":                     8,
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TRADE_FINANCE":              9,
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_OVERDRAFTS":                 10,
	"LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_BUSINESS_LOANS":             11,
}

func (x ListAccountsRequest_ListAccountsRequestProductCategory) String() string {
	return proto.EnumName(ListAccountsRequest_ListAccountsRequestProductCategory_name, int32(x))
}

func (ListAccountsRequest_ListAccountsRequestProductCategory) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f4a3e3fa51fdaf3b, []int{1, 1}
}

type BankingAccount_BankingAccountOpenStatus int32

const (
	BankingAccount_BANKING_ACCOUNT_OPEN_STATUS_OPEN   BankingAccount_BankingAccountOpenStatus = 0
	BankingAccount_BANKING_ACCOUNT_OPEN_STATUS_CLOSED BankingAccount_BankingAccountOpenStatus = 1
)

var BankingAccount_BankingAccountOpenStatus_name = map[int32]string{
	0: "BANKING_ACCOUNT_OPEN_STATUS_OPEN",
	1: "BANKING_ACCOUNT_OPEN_STATUS_CLOSED",
}

var BankingAccount_BankingAccountOpenStatus_value = map[string]int32{
	"BANKING_ACCOUNT_OPEN_STATUS_OPEN":   0,
	"BANKING_ACCOUNT_OPEN_STATUS_CLOSED": 1,
}

func (x BankingAccount_BankingAccountOpenStatus) String() string {
	return proto.EnumName(BankingAccount_BankingAccountOpenStatus_name, int32(x))
}

func (BankingAccount_BankingAccountOpenStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f4a3e3fa51fdaf3b, []int{5, 0}
}

type MetaPaginated struct {
	// The total number of pages in the full set. See [pagination](#pagination).
	TotalPages int32 `protobuf:"varint,1,opt,name=totalPages,proto3" json:"totalPages,omitempty"`
	// The total number of records in the full set. See [pagination](#pagination).
	TotalRecords         int32    `protobuf:"varint,2,opt,name=totalRecords,proto3" json:"totalRecords,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaPaginated) Reset()         { *m = MetaPaginated{} }
func (m *MetaPaginated) String() string { return proto.CompactTextString(m) }
func (*MetaPaginated) ProtoMessage()    {}
func (*MetaPaginated) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a3e3fa51fdaf3b, []int{0}
}

func (m *MetaPaginated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaPaginated.Unmarshal(m, b)
}
func (m *MetaPaginated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaPaginated.Marshal(b, m, deterministic)
}
func (m *MetaPaginated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaPaginated.Merge(m, src)
}
func (m *MetaPaginated) XXX_Size() int {
	return xxx_messageInfo_MetaPaginated.Size(m)
}
func (m *MetaPaginated) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaPaginated.DiscardUnknown(m)
}

var xxx_messageInfo_MetaPaginated proto.InternalMessageInfo

func (m *MetaPaginated) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *MetaPaginated) GetTotalRecords() int32 {
	if m != nil {
		return m.TotalRecords
	}
	return 0
}

type ListAccountsRequest struct {
	// Filters accounts based on whether they are owned by the authorised customer.  True for owned accounts, false for unowned accounts and absent for all accounts
	IsOwned bool `protobuf:"varint,1,opt,name=is_owned,json=isOwned,proto3" json:"is_owned,omitempty"`
	// Used to filter results according to open/closed status. Values can be OPEN, CLOSED or ALL. If absent then ALL is assumed
	OpenStatus ListAccountsRequest_ListAccountsRequestOpenStatus `protobuf:"varint,2,opt,name=open_status,json=openStatus,proto3,enum=aggregator.ListAccountsRequest_ListAccountsRequestOpenStatus" json:"open_status,omitempty"`
	// Page of results to request (standard pagination)
	Page int32 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	// Page size to request. Default is 25 (standard pagination)
	PageSize int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Used to filter results on the productCategory field applicable to accounts. Any one of the valid values for this field can be supplied. If absent then all accounts returned.
	ProductCategory ListAccountsRequest_ListAccountsRequestProductCategory `protobuf:"varint,5,opt,name=product_category,json=productCategory,proto3,enum=aggregator.ListAccountsRequest_ListAccountsRequestProductCategory" json:"product_category,omitempty"`
	// The customer's original standard http headers [Base64](#common-field-types) encoded, including the original User Agent header, if the customer is currently logged in to the data recipient. Mandatory for customer present calls.  Not required for unattended or unauthenticated calls.
	XCdsClientHeaders string `protobuf:"bytes,6,opt,name=x_cds_client_headers,json=xCdsClientHeaders,proto3" json:"x_cds_client_headers,omitempty"`
	// The time when the customer last logged in to the data recipient. Required for all resource calls (customer present and unattended). Not to be included for unauthenticated calls.
	XFapiAuthDate string `protobuf:"bytes,7,opt,name=x_fapi_auth_date,json=xFapiAuthDate,proto3" json:"x_fapi_auth_date,omitempty"`
	// The customer's original IP address if the customer is currently logged in to the data recipient. The presence of this header indicates that the API is being called in a customer present context. Not to be included for unauthenticated calls.
	XFapiCustomerIpAddress string `protobuf:"bytes,8,opt,name=x_fapi_customer_ip_address,json=xFapiCustomerIpAddress,proto3" json:"x_fapi_customer_ip_address,omitempty"`
	// An [RFC4122](https://tools.ietf.org/html/rfc4122) UUID used as a correlation id. If provided, the data holder must play back this value in the x-fapi-interaction-id response header. If not provided a [RFC4122] UUID value is required to be provided in the response header to track the interaction.
	XFapiInteractionId string `protobuf:"bytes,9,opt,name=x_fapi_interaction_id,json=xFapiInteractionId,proto3" json:"x_fapi_interaction_id,omitempty"`
	// Minimum version of the API end point requested by the client. Must be set to a positive integer if provided. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If all versions requested are not supported then the data holder should respond with a 406 Not Acceptable.
	XMinV string `protobuf:"bytes,10,opt,name=x_min_v,json=xMinV,proto3" json:"x_min_v,omitempty"`
	// Version of the API end point requested by the client. Must be set to a positive integer. The data holder should respond with the highest supported version between [x-min-v](#request-headers) and [x-v](#request-headers). If the value of [x-min-v](#request-headers) is equal to or higher than the value of [x-v](#request-headers) then the [x-min-v](#request-headers) header should be treated as absent. If all versions requested are not supported then the data holder should respond with a 406 Not Acceptable. See [HTTP Headers](#request-headers)
	XV                   string   `protobuf:"bytes,11,opt,name=x_v,json=xV,proto3" json:"x_v,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a3e3fa51fdaf3b, []int{1}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

func (m *ListAccountsRequest) GetIsOwned() bool {
	if m != nil {
		return m.IsOwned
	}
	return false
}

func (m *ListAccountsRequest) GetOpenStatus() ListAccountsRequest_ListAccountsRequestOpenStatus {
	if m != nil {
		return m.OpenStatus
	}
	return ListAccountsRequest_LIST_ACCOUNTS_REQUEST_OPEN_STATUS_OPEN
}

func (m *ListAccountsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListAccountsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListAccountsRequest) GetProductCategory() ListAccountsRequest_ListAccountsRequestProductCategory {
	if m != nil {
		return m.ProductCategory
	}
	return ListAccountsRequest_LIST_ACCOUNTS_REQUEST_PRODUCT_CATEGORY_TRANS_AND_SAVINGS_ACCOUNTS
}

func (m *ListAccountsRequest) GetXCdsClientHeaders() string {
	if m != nil {
		return m.XCdsClientHeaders
	}
	return ""
}

func (m *ListAccountsRequest) GetXFapiAuthDate() string {
	if m != nil {
		return m.XFapiAuthDate
	}
	return ""
}

func (m *ListAccountsRequest) GetXFapiCustomerIpAddress() string {
	if m != nil {
		return m.XFapiCustomerIpAddress
	}
	return ""
}

func (m *ListAccountsRequest) GetXFapiInteractionId() string {
	if m != nil {
		return m.XFapiInteractionId
	}
	return ""
}

func (m *ListAccountsRequest) GetXMinV() string {
	if m != nil {
		return m.XMinV
	}
	return ""
}

func (m *ListAccountsRequest) GetXV() string {
	if m != nil {
		return m.XV
	}
	return ""
}

type LinksPaginated struct {
	// URI to the first page of this set. Mandatory if this response is not the first page
	First string `protobuf:"bytes,1,opt,name=first,proto3" json:"first,omitempty"`
	// URI to the last page of this set. Mandatory if this response is not the last page
	Last string `protobuf:"bytes,2,opt,name=last,proto3" json:"last,omitempty"`
	// URI to the next page of this set. Mandatory if this response is not the last page
	Next string `protobuf:"bytes,3,opt,name=next,proto3" json:"next,omitempty"`
	// URI to the previous page of this set. Mandatory if this response is not the first page
	Prev string `protobuf:"bytes,4,opt,name=prev,proto3" json:"prev,omitempty"`
	// Fully qualified link that generated the current response document
	Self                 string   `protobuf:"bytes,5,opt,name=self,proto3" json:"self,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinksPaginated) Reset()         { *m = LinksPaginated{} }
func (m *LinksPaginated) String() string { return proto.CompactTextString(m) }
func (*LinksPaginated) ProtoMessage()    {}
func (*LinksPaginated) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a3e3fa51fdaf3b, []int{2}
}

func (m *LinksPaginated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinksPaginated.Unmarshal(m, b)
}
func (m *LinksPaginated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinksPaginated.Marshal(b, m, deterministic)
}
func (m *LinksPaginated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinksPaginated.Merge(m, src)
}
func (m *LinksPaginated) XXX_Size() int {
	return xxx_messageInfo_LinksPaginated.Size(m)
}
func (m *LinksPaginated) XXX_DiscardUnknown() {
	xxx_messageInfo_LinksPaginated.DiscardUnknown(m)
}

var xxx_messageInfo_LinksPaginated proto.InternalMessageInfo

func (m *LinksPaginated) GetFirst() string {
	if m != nil {
		return m.First
	}
	return ""
}

func (m *LinksPaginated) GetLast() string {
	if m != nil {
		return m.Last
	}
	return ""
}

func (m *LinksPaginated) GetNext() string {
	if m != nil {
		return m.Next
	}
	return ""
}

func (m *LinksPaginated) GetPrev() string {
	if m != nil {
		return m.Prev
	}
	return ""
}

func (m *LinksPaginated) GetSelf() string {
	if m != nil {
		return m.Self
	}
	return ""
}

type ResponseBankingAccountList struct {
	Data                 *ResponseBankingAccountListData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Links                *LinksPaginated                 `protobuf:"bytes,2,opt,name=links,proto3" json:"links,omitempty"`
	Meta                 *MetaPaginated                  `protobuf:"bytes,3,opt,name=meta,proto3" json:"meta,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *ResponseBankingAccountList) Reset()         { *m = ResponseBankingAccountList{} }
func (m *ResponseBankingAccountList) String() string { return proto.CompactTextString(m) }
func (*ResponseBankingAccountList) ProtoMessage()    {}
func (*ResponseBankingAccountList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a3e3fa51fdaf3b, []int{3}
}

func (m *ResponseBankingAccountList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseBankingAccountList.Unmarshal(m, b)
}
func (m *ResponseBankingAccountList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseBankingAccountList.Marshal(b, m, deterministic)
}
func (m *ResponseBankingAccountList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseBankingAccountList.Merge(m, src)
}
func (m *ResponseBankingAccountList) XXX_Size() int {
	return xxx_messageInfo_ResponseBankingAccountList.Size(m)
}
func (m *ResponseBankingAccountList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseBankingAccountList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseBankingAccountList proto.InternalMessageInfo

func (m *ResponseBankingAccountList) GetData() *ResponseBankingAccountListData {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ResponseBankingAccountList) GetLinks() *LinksPaginated {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *ResponseBankingAccountList) GetMeta() *MetaPaginated {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ResponseBankingAccountListData struct {
	// The list of accounts returned. If the filter results in an empty set then this array may have no records
	Accounts             []*BankingAccount `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResponseBankingAccountListData) Reset()         { *m = ResponseBankingAccountListData{} }
func (m *ResponseBankingAccountListData) String() string { return proto.CompactTextString(m) }
func (*ResponseBankingAccountListData) ProtoMessage()    {}
func (*ResponseBankingAccountListData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a3e3fa51fdaf3b, []int{4}
}

func (m *ResponseBankingAccountListData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseBankingAccountListData.Unmarshal(m, b)
}
func (m *ResponseBankingAccountListData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseBankingAccountListData.Marshal(b, m, deterministic)
}
func (m *ResponseBankingAccountListData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseBankingAccountListData.Merge(m, src)
}
func (m *ResponseBankingAccountListData) XXX_Size() int {
	return xxx_messageInfo_ResponseBankingAccountListData.Size(m)
}
func (m *ResponseBankingAccountListData) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseBankingAccountListData.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseBankingAccountListData proto.InternalMessageInfo

func (m *ResponseBankingAccountListData) GetAccounts() []*BankingAccount {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type BankingAccount struct {
	// A unique ID of the account adhering to the standards for ID permanence
	AccountId string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	// Date that the account was created (if known)
	CreationDate string `protobuf:"bytes,2,opt,name=creationDate,proto3" json:"creationDate,omitempty"`
	// The display name of the account as defined by the bank. This should not incorporate account numbers or PANs. If it does the values should be masked according to the rules of the MaskedAccountString common type.
	DisplayName string `protobuf:"bytes,3,opt,name=displayName,proto3" json:"displayName,omitempty"`
	// Flag indicating that the customer associated with the authorisation is an owner of the account. Does not indicate sole ownership, however. If not present then 'true' is assumed
	IsOwned bool `protobuf:"varint,4,opt,name=isOwned,proto3" json:"isOwned,omitempty"`
	// A masked version of the account. Whether BSB/Account Number, Credit Card PAN or another number
	MaskedNumber string `protobuf:"bytes,5,opt,name=maskedNumber,proto3" json:"maskedNumber,omitempty"`
	// A customer supplied nick name for the account
	Nickname string `protobuf:"bytes,6,opt,name=nickname,proto3" json:"nickname,omitempty"`
	// Open or closed status for the account. If not present then OPEN is assumed
	OpenStatus      BankingAccount_BankingAccountOpenStatus `protobuf:"varint,7,opt,name=openStatus,proto3,enum=aggregator.BankingAccount_BankingAccountOpenStatus" json:"openStatus,omitempty"`
	ProductCategory BankingProductCategory                  `protobuf:"varint,8,opt,name=productCategory,proto3,enum=aggregator.BankingProductCategory" json:"productCategory,omitempty"`
	// The unique identifier of the account as defined by the data holder (akin to model number for the account)
	ProductName          string   `protobuf:"bytes,9,opt,name=productName,proto3" json:"productName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BankingAccount) Reset()         { *m = BankingAccount{} }
func (m *BankingAccount) String() string { return proto.CompactTextString(m) }
func (*BankingAccount) ProtoMessage()    {}
func (*BankingAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a3e3fa51fdaf3b, []int{5}
}

func (m *BankingAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BankingAccount.Unmarshal(m, b)
}
func (m *BankingAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BankingAccount.Marshal(b, m, deterministic)
}
func (m *BankingAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BankingAccount.Merge(m, src)
}
func (m *BankingAccount) XXX_Size() int {
	return xxx_messageInfo_BankingAccount.Size(m)
}
func (m *BankingAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_BankingAccount.DiscardUnknown(m)
}

var xxx_messageInfo_BankingAccount proto.InternalMessageInfo

func (m *BankingAccount) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *BankingAccount) GetCreationDate() string {
	if m != nil {
		return m.CreationDate
	}
	return ""
}

func (m *BankingAccount) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *BankingAccount) GetIsOwned() bool {
	if m != nil {
		return m.IsOwned
	}
	return false
}

func (m *BankingAccount) GetMaskedNumber() string {
	if m != nil {
		return m.MaskedNumber
	}
	return ""
}

func (m *BankingAccount) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *BankingAccount) GetOpenStatus() BankingAccount_BankingAccountOpenStatus {
	if m != nil {
		return m.OpenStatus
	}
	return BankingAccount_BANKING_ACCOUNT_OPEN_STATUS_OPEN
}

func (m *BankingAccount) GetProductCategory() BankingProductCategory {
	if m != nil {
		return m.ProductCategory
	}
	return BankingProductCategory_TRANS_AND_SAVINGS_ACCOUNTS
}

func (m *BankingAccount) GetProductName() string {
	if m != nil {
		return m.ProductName
	}
	return ""
}

type ResponseBankingAllAccountList struct {
	ProductCategoryMap   map[string]int32  `protobuf:"bytes,1,rep,name=productCategoryMap,proto3" json:"productCategoryMap,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	TotalOpenAccounts    int32             `protobuf:"varint,2,opt,name=totalOpenAccounts,proto3" json:"totalOpenAccounts,omitempty"`
	TotalClosedAccounts  int32             `protobuf:"varint,3,opt,name=totalClosedAccounts,proto3" json:"totalClosedAccounts,omitempty"`
	Accounts             map[string]string `protobuf:"bytes,4,rep,name=accounts,proto3" json:"accounts,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ResponseBankingAllAccountList) Reset()         { *m = ResponseBankingAllAccountList{} }
func (m *ResponseBankingAllAccountList) String() string { return proto.CompactTextString(m) }
func (*ResponseBankingAllAccountList) ProtoMessage()    {}
func (*ResponseBankingAllAccountList) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4a3e3fa51fdaf3b, []int{6}
}

func (m *ResponseBankingAllAccountList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseBankingAllAccountList.Unmarshal(m, b)
}
func (m *ResponseBankingAllAccountList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseBankingAllAccountList.Marshal(b, m, deterministic)
}
func (m *ResponseBankingAllAccountList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseBankingAllAccountList.Merge(m, src)
}
func (m *ResponseBankingAllAccountList) XXX_Size() int {
	return xxx_messageInfo_ResponseBankingAllAccountList.Size(m)
}
func (m *ResponseBankingAllAccountList) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseBankingAllAccountList.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseBankingAllAccountList proto.InternalMessageInfo

func (m *ResponseBankingAllAccountList) GetProductCategoryMap() map[string]int32 {
	if m != nil {
		return m.ProductCategoryMap
	}
	return nil
}

func (m *ResponseBankingAllAccountList) GetTotalOpenAccounts() int32 {
	if m != nil {
		return m.TotalOpenAccounts
	}
	return 0
}

func (m *ResponseBankingAllAccountList) GetTotalClosedAccounts() int32 {
	if m != nil {
		return m.TotalClosedAccounts
	}
	return 0
}

func (m *ResponseBankingAllAccountList) GetAccounts() map[string]string {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func init() {
	proto.RegisterEnum("aggregator.BankingProductCategory", BankingProductCategory_name, BankingProductCategory_value)
	proto.RegisterEnum("aggregator.ListAccountsRequest_ListAccountsRequestOpenStatus", ListAccountsRequest_ListAccountsRequestOpenStatus_name, ListAccountsRequest_ListAccountsRequestOpenStatus_value)
	proto.RegisterEnum("aggregator.ListAccountsRequest_ListAccountsRequestProductCategory", ListAccountsRequest_ListAccountsRequestProductCategory_name, ListAccountsRequest_ListAccountsRequestProductCategory_value)
	proto.RegisterEnum("aggregator.BankingAccount_BankingAccountOpenStatus", BankingAccount_BankingAccountOpenStatus_name, BankingAccount_BankingAccountOpenStatus_value)
	proto.RegisterType((*MetaPaginated)(nil), "aggregator.MetaPaginated")
	proto.RegisterType((*ListAccountsRequest)(nil), "aggregator.ListAccountsRequest")
	proto.RegisterType((*LinksPaginated)(nil), "aggregator.LinksPaginated")
	proto.RegisterType((*ResponseBankingAccountList)(nil), "aggregator.ResponseBankingAccountList")
	proto.RegisterType((*ResponseBankingAccountListData)(nil), "aggregator.ResponseBankingAccountListData")
	proto.RegisterType((*BankingAccount)(nil), "aggregator.BankingAccount")
	proto.RegisterType((*ResponseBankingAllAccountList)(nil), "aggregator.ResponseBankingAllAccountList")
	proto.RegisterMapType((map[string]string)(nil), "aggregator.ResponseBankingAllAccountList.AccountsEntry")
	proto.RegisterMapType((map[string]int32)(nil), "aggregator.ResponseBankingAllAccountList.ProductCategoryMapEntry")
}

func init() { proto.RegisterFile("aggregator/customob.proto", fileDescriptor_f4a3e3fa51fdaf3b) }

var fileDescriptor_f4a3e3fa51fdaf3b = []byte{
	// 1316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdf, 0x72, 0xda, 0x46,
	0x17, 0x0f, 0xb6, 0xb1, 0xe1, 0x60, 0x13, 0x65, 0xf3, 0x4f, 0xe6, 0x4b, 0x32, 0x1e, 0xcd, 0xf7,
	0x25, 0x8e, 0x27, 0x31, 0x31, 0xf9, 0xd2, 0xa4, 0x6e, 0x9b, 0x56, 0x16, 0x0a, 0x61, 0x8a, 0x05,
	0x5d, 0x09, 0x4f, 0x7b, 0xd3, 0x9d, 0x35, 0xda, 0x60, 0x8d, 0x41, 0x52, 0xa4, 0x85, 0xe2, 0x5c,
	0xf6, 0xae, 0xd7, 0xed, 0x23, 0x74, 0xfa, 0x16, 0x9d, 0xe9, 0x7d, 0x2f, 0xfb, 0x0a, 0x7d, 0x84,
	0xde, 0x76, 0xa6, 0xa3, 0x95, 0xc0, 0x40, 0x30, 0x26, 0xbd, 0xf2, 0xee, 0x39, 0xe7, 0xf7, 0xf3,
	0x39, 0x3a, 0xbb, 0xe7, 0xb7, 0xc0, 0x26, 0x6d, 0xb7, 0x03, 0xd6, 0xa6, 0xdc, 0x0b, 0x8a, 0xad,
	0x5e, 0xc8, 0xbd, 0xae, 0x77, 0xbc, 0xeb, 0x07, 0x1e, 0xf7, 0x10, 0x9c, 0xbb, 0x0a, 0x77, 0xda,
	0x9e, 0xd7, 0xee, 0xb0, 0x22, 0xf5, 0x9d, 0x22, 0x75, 0x5d, 0x8f, 0x53, 0xee, 0x78, 0x6e, 0x18,
	0x47, 0x2a, 0x26, 0x6c, 0x1c, 0x32, 0x4e, 0x1b, 0xb4, 0xed, 0xb8, 0x94, 0x33, 0x1b, 0xdd, 0x03,
	0xe0, 0x1e, 0xa7, 0x9d, 0x06, 0x6d, 0xb3, 0x50, 0x4e, 0x6d, 0xa5, 0xb6, 0xd3, 0x78, 0xcc, 0x82,
	0x14, 0x58, 0x17, 0x3b, 0xcc, 0x5a, 0x5e, 0x60, 0x87, 0xf2, 0x92, 0x88, 0x98, 0xb0, 0x29, 0xbf,
	0xe5, 0xe0, 0x7a, 0xcd, 0x09, 0xb9, 0xda, 0x6a, 0x79, 0x3d, 0x97, 0x87, 0x98, 0xbd, 0xed, 0xb1,
	0x90, 0xa3, 0x4d, 0xc8, 0x38, 0x21, 0xf1, 0xbe, 0x73, 0x99, 0x2d, 0x98, 0x33, 0x78, 0xcd, 0x09,
	0xeb, 0xd1, 0x16, 0x7d, 0x0b, 0x39, 0xcf, 0x67, 0x2e, 0x09, 0x39, 0xe5, 0xbd, 0x98, 0x35, 0x5f,
	0xfa, 0x6c, 0xf7, 0xbc, 0x8e, 0xdd, 0x19, 0x84, 0xb3, 0x6c, 0x75, 0x9f, 0xb9, 0xa6, 0x20, 0xc1,
	0xe0, 0x8d, 0xd6, 0x08, 0xc1, 0x8a, 0x4f, 0xdb, 0x4c, 0x5e, 0x16, 0xe9, 0x8a, 0x35, 0xfa, 0x0f,
	0x64, 0xa3, 0xbf, 0x24, 0x74, 0xde, 0x31, 0x79, 0x45, 0x38, 0x32, 0x91, 0xc1, 0x74, 0xde, 0x31,
	0xd4, 0x05, 0xc9, 0x0f, 0x3c, 0xbb, 0xd7, 0xe2, 0xa4, 0x45, 0x39, 0x6b, 0x7b, 0xc1, 0x99, 0x9c,
	0x16, 0x59, 0x1d, 0xfc, 0x8b, 0xac, 0x1a, 0x31, 0x95, 0x96, 0x30, 0xe1, 0xab, 0xfe, 0xa4, 0x01,
	0x15, 0xe1, 0xc6, 0x80, 0xb4, 0xec, 0x90, 0xb4, 0x3a, 0x0e, 0x73, 0x39, 0x39, 0x61, 0xd4, 0x66,
	0x41, 0x28, 0xaf, 0x6e, 0xa5, 0xb6, 0xb3, 0xf8, 0xda, 0x40, 0xb3, 0x43, 0x4d, 0x78, 0x5e, 0xc7,
	0x0e, 0xf4, 0x00, 0xa4, 0x01, 0x79, 0x43, 0x7d, 0x87, 0xd0, 0x1e, 0x3f, 0x21, 0x36, 0xe5, 0x4c,
	0x5e, 0x13, 0xc1, 0x1b, 0x83, 0x57, 0xd4, 0x77, 0xd4, 0x1e, 0x3f, 0x29, 0x53, 0xce, 0xd0, 0x3e,
	0x14, 0x92, 0xc0, 0xf8, 0x90, 0xb0, 0x80, 0x38, 0x3e, 0xa1, 0xb6, 0x1d, 0xb0, 0x30, 0x94, 0x33,
	0x02, 0x72, 0x4b, 0x40, 0xb4, 0xc4, 0x5f, 0xf5, 0xd5, 0xd8, 0x8b, 0xf6, 0xe0, 0x66, 0x82, 0x75,
	0x5c, 0xce, 0x02, 0xda, 0x8a, 0x8e, 0x0e, 0x71, 0x6c, 0x39, 0x2b, 0x60, 0x48, 0xc0, 0xaa, 0xe7,
	0xae, 0xaa, 0x8d, 0x6e, 0xc1, 0xda, 0x80, 0x74, 0x1d, 0x97, 0xf4, 0x65, 0x10, 0x41, 0xe9, 0xc1,
	0xa1, 0xe3, 0x1e, 0xa1, 0xab, 0xb0, 0x3c, 0x20, 0x7d, 0x39, 0x27, 0x6c, 0x4b, 0x83, 0x23, 0xe5,
	0xe7, 0x14, 0xdc, 0x9d, 0xdb, 0x3f, 0xb4, 0x03, 0xf7, 0x6b, 0x55, 0xd3, 0x22, 0xaa, 0xa6, 0xd5,
	0x9b, 0x86, 0x65, 0x12, 0xac, 0x7f, 0xd5, 0xd4, 0x4d, 0x8b, 0xd4, 0x1b, 0xba, 0x41, 0x4c, 0x4b,
	0xb5, 0x9a, 0xa6, 0x58, 0x4b, 0x57, 0xd0, 0x23, 0xd8, 0xbe, 0x3c, 0x56, 0xab, 0xd5, 0x4d, 0xbd,
	0x2c, 0xa5, 0xd0, 0x43, 0xf8, 0xdf, 0xe5, 0xd1, 0x6a, 0xad, 0x26, 0x2d, 0x29, 0x7f, 0xa5, 0x41,
	0xb9, 0xbc, 0xa1, 0x48, 0x07, 0x75, 0x36, 0x63, 0x03, 0xd7, 0xcb, 0x4d, 0xcd, 0x22, 0x9a, 0x6a,
	0xe9, 0x95, 0x3a, 0xfe, 0x86, 0x58, 0x58, 0x35, 0x4c, 0xa2, 0x1a, 0x65, 0x62, 0xaa, 0x47, 0x55,
	0xa3, 0x62, 0x8e, 0x30, 0xd2, 0x15, 0xf4, 0x02, 0xfe, 0xbf, 0x28, 0x8d, 0x8e, 0x0f, 0x49, 0x59,
	0x6f, 0xd4, 0xcd, 0xaa, 0x65, 0x4a, 0x29, 0xf4, 0x1c, 0x9e, 0x2e, 0x9e, 0xc0, 0x91, 0x5e, 0x23,
	0x9a, 0x8a, 0xcb, 0xa6, 0xb4, 0x84, 0x34, 0xf8, 0x7c, 0x41, 0x20, 0xd6, 0x2b, 0xcd, 0x9a, 0x6a,
	0xe9, 0x65, 0x62, 0xe1, 0xe6, 0x18, 0x42, 0x5a, 0x46, 0x5f, 0xc0, 0xa7, 0x0b, 0x93, 0x98, 0xd5,
	0xb2, 0x6e, 0x58, 0x55, 0xb5, 0x46, 0x0e, 0xeb, 0xd8, 0xaa, 0xa8, 0x15, 0xdd, 0x94, 0x56, 0xd0,
	0x4b, 0xd8, 0x5f, 0x90, 0x41, 0xc3, 0x7a, 0x59, 0x7c, 0x3f, 0xed, 0x35, 0xae, 0x24, 0x65, 0xa4,
	0xd1, 0x33, 0xd8, 0x5b, 0x10, 0xdf, 0xd0, 0xb1, 0x49, 0x6a, 0x75, 0xd5, 0x30, 0xa5, 0xd5, 0x0f,
	0xf8, 0x6c, 0x87, 0x2a, 0xae, 0x54, 0x8d, 0x04, 0xb8, 0x86, 0xf6, 0xe0, 0xf1, 0x82, 0xc0, 0x9a,
	0xae, 0x9a, 0xba, 0x29, 0x65, 0x3e, 0xa4, 0xb9, 0x58, 0x2d, 0xeb, 0xe4, 0x55, 0xd5, 0x50, 0x0d,
	0x4d, 0x97, 0xb2, 0x1f, 0x50, 0x5c, 0xfd, 0x48, 0xc7, 0x65, 0xac, 0xbe, 0xb2, 0x4c, 0x09, 0xd0,
	0xc7, 0xf0, 0x6c, 0x41, 0xd8, 0x41, 0xd3, 0xac, 0x1a, 0xba, 0x39, 0xfc, 0x2e, 0x39, 0xa5, 0x0f,
	0xf9, 0x9a, 0xe3, 0x9e, 0x86, 0xe7, 0xc2, 0x70, 0x03, 0xd2, 0x6f, 0x9c, 0x20, 0xe4, 0x62, 0x72,
	0x67, 0x71, 0xbc, 0x89, 0xe6, 0x6a, 0x87, 0x86, 0x5c, 0x0c, 0xec, 0x2c, 0x16, 0xeb, 0xc8, 0xe6,
	0xb2, 0x01, 0x17, 0xb3, 0x36, 0x8b, 0xc5, 0x5a, 0xcc, 0xdf, 0x80, 0xf5, 0xc5, 0x98, 0xcd, 0x62,
	0xb1, 0x8e, 0x6c, 0x21, 0xeb, 0xbc, 0x11, 0x63, 0x35, 0x8b, 0xc5, 0x5a, 0xf9, 0x35, 0x05, 0x05,
	0xcc, 0x42, 0xdf, 0x73, 0x43, 0x76, 0x40, 0xdd, 0x53, 0xc7, 0x6d, 0x27, 0x37, 0x2f, 0xba, 0x84,
	0xe8, 0x25, 0xac, 0xd8, 0x94, 0x53, 0x91, 0x43, 0xae, 0xb4, 0x33, 0x3e, 0x89, 0x2f, 0x46, 0x95,
	0x29, 0xa7, 0x58, 0xe0, 0xd0, 0x13, 0x48, 0x77, 0xa2, 0xb2, 0x44, 0xbe, 0xb9, 0x52, 0x61, 0x72,
	0x94, 0x8f, 0xd7, 0x8b, 0xe3, 0x40, 0xf4, 0x18, 0x56, 0xba, 0x8c, 0x53, 0x51, 0x4c, 0xae, 0xb4,
	0x39, 0x0e, 0x98, 0x10, 0x4e, 0x2c, 0xc2, 0x94, 0xaf, 0xe1, 0xde, 0xfc, 0x44, 0xd0, 0x47, 0x90,
	0xa1, 0xc9, 0x2c, 0x91, 0x53, 0x5b, 0xcb, 0xd3, 0x59, 0x4c, 0xa2, 0xf0, 0x28, 0x56, 0xf9, 0x7b,
	0x19, 0xf2, 0x93, 0x4e, 0x74, 0x07, 0xb2, 0x89, 0xbb, 0x6a, 0x27, 0x6d, 0x39, 0x37, 0x44, 0x4a,
	0xdd, 0x0a, 0x98, 0x50, 0xfb, 0x48, 0x08, 0x92, 0x16, 0x4d, 0xd8, 0xd0, 0x16, 0xe4, 0x6c, 0x27,
	0xf4, 0x3b, 0xf4, 0xcc, 0xa0, 0x5d, 0x96, 0x74, 0x6c, 0xdc, 0x84, 0x64, 0x18, 0x6a, 0xb4, 0xe8,
	0xdd, 0x98, 0x64, 0x2b, 0xb0, 0xde, 0xa5, 0xe1, 0x29, 0xb3, 0x8d, 0x5e, 0xf7, 0x98, 0x05, 0x49,
	0x1b, 0x27, 0x6c, 0xa8, 0x00, 0x19, 0xd7, 0x69, 0x9d, 0xba, 0x11, 0x79, 0x2c, 0x65, 0xa3, 0x3d,
	0x32, 0x61, 0x4c, 0xa0, 0x85, 0x76, 0xe5, 0x4b, 0x4f, 0x2f, 0xfe, 0x14, 0x53, 0xdb, 0x0b, 0x74,
	0xbe, 0x06, 0xd3, 0xd2, 0x2a, 0x24, 0x2e, 0x5f, 0x52, 0x66, 0x30, 0x5f, 0xaa, 0xca, 0x5b, 0x90,
	0x4b, 0x4c, 0xe2, 0xf3, 0xc4, 0xaa, 0x37, 0x6e, 0x52, 0x4e, 0x40, 0xbe, 0x28, 0x2f, 0xf4, 0x5f,
	0xd8, 0x3a, 0x50, 0x8d, 0x2f, 0xab, 0x46, 0x65, 0x78, 0x03, 0x67, 0x29, 0xd7, 0x7d, 0x50, 0xe6,
	0x45, 0x0d, 0x35, 0x4b, 0xf9, 0x7d, 0x19, 0xee, 0x4e, 0x1f, 0xad, 0x4e, 0x67, 0xfc, 0x72, 0xbc,
	0x05, 0x34, 0x55, 0xc0, 0x21, 0xf5, 0x93, 0x33, 0xa6, 0xce, 0xbb, 0x2a, 0x13, 0x34, 0xbb, 0x8d,
	0xf7, 0x38, 0x74, 0x97, 0x07, 0x67, 0x78, 0x06, 0x39, 0x7a, 0x04, 0xd7, 0xc4, 0xcb, 0x2f, 0xaa,
	0x7a, 0xa8, 0x90, 0xc9, 0x93, 0xf0, 0x7d, 0x07, 0x7a, 0x02, 0xd7, 0x85, 0x51, 0xeb, 0x78, 0x21,
	0xb3, 0x47, 0xf1, 0xf1, 0x9b, 0x6c, 0x96, 0x0b, 0x99, 0x63, 0x97, 0x65, 0x45, 0x14, 0xf2, 0x7c,
	0xf1, 0x42, 0x86, 0x2c, 0x71, 0xfa, 0x23, 0xa2, 0x82, 0x0e, 0xb7, 0x2f, 0xa8, 0x11, 0x49, 0xb0,
	0x7c, 0xca, 0xce, 0x92, 0xbb, 0x14, 0x2d, 0xa3, 0xb1, 0xd7, 0xa7, 0x9d, 0x1e, 0x4b, 0xaa, 0x8a,
	0x37, 0xfb, 0x4b, 0x2f, 0x52, 0x85, 0x4f, 0x60, 0x63, 0xe2, 0x3f, 0x5c, 0x06, 0xce, 0x8e, 0x81,
	0x77, 0x7e, 0x5a, 0x82, 0x5b, 0xb3, 0x4f, 0x21, 0xba, 0x07, 0x85, 0xb9, 0x6f, 0x84, 0x6b, 0xb0,
	0x31, 0x2d, 0xfe, 0x12, 0xac, 0x4f, 0xa9, 0xfa, 0x1d, 0x90, 0xe7, 0xc8, 0xf5, 0x26, 0xdc, 0xbc,
	0x48, 0x87, 0x6f, 0xc3, 0xf5, 0xd9, 0x02, 0x9b, 0x07, 0x98, 0x50, 0x4e, 0x09, 0xd6, 0xa7, 0x24,
	0x11, 0x60, 0x75, 0xa4, 0x75, 0x51, 0x92, 0x53, 0x22, 0x96, 0x07, 0x98, 0x50, 0x27, 0x04, 0xf9,
	0x69, 0xd9, 0x29, 0xfd, 0x92, 0x3a, 0xbf, 0x4f, 0xa3, 0x36, 0x9b, 0x2c, 0xe8, 0x3b, 0x2d, 0x86,
	0x7e, 0x48, 0xc1, 0x55, 0xf1, 0x14, 0x1b, 0xb5, 0x39, 0x44, 0x73, 0x66, 0x67, 0xe1, 0xe1, 0xc2,
	0x47, 0x45, 0x79, 0xfc, 0xfd, 0x1f, 0x7f, 0xfe, 0xb8, 0xf4, 0x40, 0x51, 0x8a, 0x63, 0x3f, 0xaa,
	0xfa, 0x7b, 0xc5, 0xe3, 0x38, 0xba, 0x48, 0x3b, 0x9d, 0xe1, 0xf1, 0xd9, 0x4f, 0xed, 0x6c, 0xa7,
	0x8e, 0x57, 0xc5, 0xcf, 0xa7, 0xa7, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x8d, 0xc3, 0x05, 0x7a,
	0x85, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BankingAggregatorServiceClient is the client API for BankingAggregatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BankingAggregatorServiceClient interface {
	// Obtain a list of accounts
	ListAllAccounts(ctx context.Context, opts ...grpc.CallOption) (BankingAggregatorService_ListAllAccountsClient, error)
}

type bankingAggregatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBankingAggregatorServiceClient(cc grpc.ClientConnInterface) BankingAggregatorServiceClient {
	return &bankingAggregatorServiceClient{cc}
}

func (c *bankingAggregatorServiceClient) ListAllAccounts(ctx context.Context, opts ...grpc.CallOption) (BankingAggregatorService_ListAllAccountsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BankingAggregatorService_serviceDesc.Streams[0], "/aggregator.BankingAggregatorService/ListAllAccounts", opts...)
	if err != nil {
		return nil, err
	}
	x := &bankingAggregatorServiceListAllAccountsClient{stream}
	return x, nil
}

type BankingAggregatorService_ListAllAccountsClient interface {
	Send(*BankingAccount) error
	CloseAndRecv() (*ResponseBankingAllAccountList, error)
	grpc.ClientStream
}

type bankingAggregatorServiceListAllAccountsClient struct {
	grpc.ClientStream
}

func (x *bankingAggregatorServiceListAllAccountsClient) Send(m *BankingAccount) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bankingAggregatorServiceListAllAccountsClient) CloseAndRecv() (*ResponseBankingAllAccountList, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ResponseBankingAllAccountList)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BankingAggregatorServiceServer is the server API for BankingAggregatorService service.
type BankingAggregatorServiceServer interface {
	// Obtain a list of accounts
	ListAllAccounts(BankingAggregatorService_ListAllAccountsServer) error
}

// UnimplementedBankingAggregatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBankingAggregatorServiceServer struct {
}

func (*UnimplementedBankingAggregatorServiceServer) ListAllAccounts(srv BankingAggregatorService_ListAllAccountsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListAllAccounts not implemented")
}

func RegisterBankingAggregatorServiceServer(s *grpc.Server, srv BankingAggregatorServiceServer) {
	s.RegisterService(&_BankingAggregatorService_serviceDesc, srv)
}

func _BankingAggregatorService_ListAllAccounts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BankingAggregatorServiceServer).ListAllAccounts(&bankingAggregatorServiceListAllAccountsServer{stream})
}

type BankingAggregatorService_ListAllAccountsServer interface {
	SendAndClose(*ResponseBankingAllAccountList) error
	Recv() (*BankingAccount, error)
	grpc.ServerStream
}

type bankingAggregatorServiceListAllAccountsServer struct {
	grpc.ServerStream
}

func (x *bankingAggregatorServiceListAllAccountsServer) SendAndClose(m *ResponseBankingAllAccountList) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bankingAggregatorServiceListAllAccountsServer) Recv() (*BankingAccount, error) {
	m := new(BankingAccount)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BankingAggregatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aggregator.BankingAggregatorService",
	HandlerType: (*BankingAggregatorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListAllAccounts",
			Handler:       _BankingAggregatorService_ListAllAccounts_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "aggregator/customob.proto",
}
